repos:
  # - repo: https://gitlab.com/pycqa/flake8.git
  #   rev: 3.8.3
  #   hooks:
  #     - id: flake8
  # - repo: https://github.com/asottile/seed-isort-config
  #   rev: v2.2.0
  #   hooks:
  #     - id: seed-isort-config
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 4.3.21
  #   hooks:
  #     - id: isort
  # - repo: https://github.com/pre-commit/mirrors-yapf
  #   rev: v0.30.0
  #   hooks:
  #     - id: yapf
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v3.1.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: check-yaml
  #     - id: end-of-file-fixer
  #     - id: requirements-txt-fixer
  #     - id: double-quote-string-fixer
  #     - id: check-merge-conflict
  #     - id: fix-encoding-pragma
  #       args: ["--remove"]
  #     - id: mixed-line-ending
  #       args: ["--fix=lf"]
  # - repo: https://github.com/jumanjihouse/pre-commit-hooks
  #   rev: 2.1.4
  #   hooks:
  #     - id: markdownlint
  #       args: ["-r", "~MD002,~MD013,~MD024,~MD029,~MD033,~MD034,~MD036"]
  # - repo: https://github.com/myint/docformatter
  #   rev: v1.3.1
  #   hooks:
  #     - id: docformatter
  #       args: ["--in-place", "--wrap-descriptions", "79"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
        args: ["--config-file=.mypy.ini"]
        additional_dependencies: [numpy==1.19.5, types-PyYAML, attrs==21.2.*, types-requests, types-Deprecated, types-docutils, types_futures, types-python-dateutil]
        exclude: "ci|configs|data|demo|docker|docs|experiments|resources|tools"
