# Description.
model_template_id: Face_Detection_0207
name: face-detection-0207
task_type: DETECTION
task_family: VISION
instantiation: "CLASS"
summary: Face Detection based on ShuffleNetV2 (SSD).
application:
  ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mmdet.apis.ote.apis.detection.OTEDetectionTrainingTask
  openvino: mmdet.apis.ote.apis.detection.OpenVINODetectionTask
  nncf: mmdet.apis.ote.apis.detection.OTEDetectionNNCFTask

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdet/apis/ote/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 32
      learning_rate:
        default_value: 0.05
      learning_rate_warmup_iters:
        default_value: 1200
      num_iters:
        default_value: 70
    nncf_optimization:
      enable_quantization:
        default_value: false
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 0.01

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 1.04
size: 0.81

# Obsolete
# gpu_nums: 1