# Description.
name: face-detection-0205
domain: Object Detection
summary: Face Detection based on MobileNetV2 (FCOS).

# Algo backend.
# Would be better to have something more precise and self-contained, e.g.:  docker image or path to Python venv activation script?
framework: OTEDetection v2.9.1

# Should be revisited?
applications:
  ~

# Optional? requirements to the dataset. Should be revisited?
dataset_requirements:
  ~

# Task implementation.
task:
  base: mmdet.apis.ote.apis.detection.OTEDetectionTask
  openvino: mmdet.apis.ote.apis.detection.OpenVINODetectionTask

# Task and hyperparameters.
hyper_parameters:
  impl: mmdet.apis.ote.apis.detection.OTEDetectionConfig
  # Would be good to have different groups of parameters:
  # - Basic: Shown to the user in the first place and editable by him.
  # - Advanced: Editable by the user used the "advanced" section.
  # - Hidden/internal: non-editable by the user. Used to pass some parameters to the Task at its initilization.
  params:
    learning_parameters:
      batch_size: 1 # Original batch size 16
      learning_rate: 0.05
      num_iters: 70 # this is number of epochs
    algo_backend:
      model: model.py

# Available model optimizations and their configuration.
optimization:
  output_format:
    onnx:
      default: true
    openvino:
      default: true
      input_format: BGR
      normalize_input: true
      precision: FP32
      pot: ~
  nncf:
    quantization:
      config: compression_config.json
      default: false
    sparsity:
      config: compression_config.json
      default: false

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Inference options. Defined by OpenVINO capabilities, not Algo Backend or Platform.
inference_target:
  - CPU
  - iGPU
  - VPU

# Some meta information, which may be used for model recommendation. In general, metrics are non-static, hence has to be updated.
metrics:
- display_name: AP @ [IoU=0.50:0.95]
  key: bbox
  unit: '%'
  value: 22.7
- display_name: AP for faces > 64x64
  key: ap_64x64
  unit: '%'
  value: 93.995
- display_name: WiderFace Easy
  key: widerface_e
  unit: '%'
  value: 92.606
- display_name: WiderFace Medium
  key: widerface_m
  unit: '%'
  value: 87.556
- display_name: WiderFace Hard
  key: widerface_h
  unit: '%'
  value: 56.221
- display_name: Size
  key: size
  unit: Mp
  value: 2.02
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 2.94